# Missing Indicator Imputation

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [2]:
df = pd.read_csv('train (5).csv', usecols=['Age', 'Fare', 'Survived'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

## Create X & Y

In [3]:
x = df.drop(columns=['Survived'])
y = df['Survived']

## Train & Test Split

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [5]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

## Review Without “Missing Indicator Method” Technique

In [6]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.fit_transform(x_test)

In [7]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [8]:
x_test_trf

array([[ 42.    ,  26.2875],
       [ 21.    ,   8.05  ],
       [ 24.    ,  65.    ],
       [ 28.    ,  56.4958],
       [ 17.    ,   7.925 ],
       [ 30.    ,   7.8958],
       [ 80.    ,  30.    ],
       [ 25.    ,   7.25  ],
       [ 50.    , 133.65  ],
       [ 25.    ,  26.    ],
       [ 35.    ,  26.    ],
       [ 35.    ,  90.    ],
       [ 55.    ,  16.    ],
       [ 29.3728,  56.4958],
       [ 29.3728,  56.4958],
       [ 19.    ,   7.8542],
       [ 29.3728,  15.2458],
       [ 49.    ,   0.    ],
       [ 18.    ,  14.4542],
       [ 65.    ,   7.75  ],
       [ 18.    , 108.9   ],
       [ 29.3728,  22.3583],
       [ 16.    ,  18.    ],
       [ 21.    ,   9.825 ],
       [ 19.    ,   6.75  ],
       [  1.    ,  11.1333],
       [ 50.    ,  10.5   ],
       [ 37.    ,  53.1   ],
       [ 28.    ,   9.5   ],
       [ 54.    ,  14.    ],
       [ 20.    ,   7.925 ],
       [ 36.    ,   0.    ],
       [  6.    ,  31.275 ],
       [ 29.3728,  50.    ],
       [ 40.    ,  31.    ],
       [ 26.    ,  16.1   ],
       [ 30.    ,  93.5   ],
       [  1.    ,  46.9   ],
       [ 29.3728,   7.8958],
       [ 35.    ,  10.5   ],
       [ 38.    ,   7.05  ],
       [ 44.    ,  16.1   ],
       [ 22.    ,   7.75  ],
       [ 18.    ,   6.4958],
       [ 21.    ,   8.4333],
       [ 29.3728, 227.525 ],
       [ 21.    ,  77.9583],
       [ 29.3728,   8.6625],
       [ 22.    ,   7.225 ],
       [ 27.    ,  10.5   ],
       [ 29.3728,   8.05  ],
       [ 51.    ,  26.55  ],
       [ 28.    ,  33.    ],
       [ 47.    ,  38.5   ],
       [ 32.    ,  10.5   ],
       [ 48.    ,  52.    ],
       [ 10.    ,  24.15  ],
       [ 21.    ,   8.6625],
       [ 51.    ,   7.0542],
       [ 32.    ,   7.925 ],
       [ 42.    ,  13.    ],
       [  2.    ,  26.    ],
       [ 35.    ,   8.05  ],
       [ 29.3728,   7.25  ],
       [  2.    ,  10.4625],
       [ 33.    ,   9.5   ],
       [ 48.    ,  25.9292],
       [ 55.    ,  30.5   ],
       [  1.    ,  39.6875],
       [ 17.    ,   7.0542],
       [ 24.    ,  15.85  ],
       [ 74.    ,   7.775 ],
       [ 29.3728,  24.15  ],
       [ 28.    ,   7.7958],
       [ 26.    ,   7.8542],
       [  1.    ,  39.    ],
       [ 18.    ,   8.05  ],
       [  3.    ,  26.    ],
       [ 48.    ,  39.6   ],
       [ 32.    ,  56.4958],
       [ 19.    ,  91.0792],
       [ 29.3728,  42.4   ],
       [ 70.    ,  10.5   ],
       [ 34.    ,  26.    ],
       [ 39.    , 110.8833],
       [ 17.    ,  10.5   ],
       [ 38.    ,   8.6625],
       [ 29.3728,   7.8958],
       [ 30.    ,  21.    ],
       [ 28.    ,  13.    ],
       [ 29.3728,   7.725 ],
       [ 19.    ,   8.1583],
       [ 29.    ,   7.75  ],
       [ 29.3728,   7.8958],
       [ 44.    ,   7.925 ],
       [ 22.    ,  41.5792],
       [ 21.    ,  34.375 ],
       [ 41.    ,  19.5   ],
       [ 29.3728,   7.225 ],
       [ 25.    ,  55.4417],
       [  0.92  , 151.55  ],
       [ 44.    ,  26.    ],
       [ 19.    ,  26.    ],
       [ 30.    ,  56.9292],
       [ 20.    ,   9.5   ],
       [  5.    ,  12.475 ],
       [  4.    ,  39.    ],
       [ 29.3728,  16.1   ],
       [ 38.    ,   0.    ],
       [ 28.    ,  22.525 ],
       [ 29.3728,  30.    ],
       [ 29.    ,   7.775 ],
       [ 49.    ,  89.1042],
       [ 19.    ,  14.5   ],
       [ 18.    , 262.375 ],
       [ 31.    ,  26.25  ],
       [ 27.    ,   7.7958],
       [ 36.    , 120.    ],
       [  8.    ,  36.75  ],
       [  2.    ,  21.075 ],
       [ 63.    ,  77.9583],
       [ 31.    ,   7.75  ],
       [ 29.3728,   0.    ],
       [ 25.    ,  13.    ],
       [ 20.5   ,   7.25  ],
       [ 29.3728,   7.8958],
       [ 64.    , 263.    ],
       [ 19.    ,  26.    ],
       [ 18.    ,   7.775 ],
       [ 29.3728,   0.    ],
       [ 29.3728,   7.8958],
       [ 11.    ,  18.7875],
       [ 15.    ,  14.4542],
       [ 22.    ,  55.    ],
       [ 50.    ,  13.    ],
       [ 28.    ,  14.4   ],
       [ 39.    ,  13.    ],
       [ 29.3728,   8.05  ],
       [ 39.    ,   7.925 ],
       [ 24.    ,  16.1   ],
       [ 23.    ,   7.925 ],
       [ 17.    ,  57.    ],
       [ 44.    ,  26.    ],
       [ 23.    ,  13.7917],
       [ 29.3728,  26.55  ],
       [ 52.    ,  78.2667],
       [ 24.5   ,   8.05  ],
       [ 55.5   ,   8.05  ],
       [ 18.    ,   7.7958],
       [ 18.    ,  13.    ],
       [ 45.    ,  83.475 ],
       [ 31.    ,  18.    ],
       [ 30.5   ,   8.05  ],
       [ 42.    ,   8.4042],
       [ 29.3728,   7.75  ],
       [ 36.    ,   7.4958],
       [ 34.    ,  26.55  ],
       [ 54.    ,  78.2667],
       [ 15.    ,   8.0292],
       [ 25.    ,   7.775 ],
       [ 26.    ,  30.    ],
       [ 29.3728,   8.1125],
       [ 19.    ,   8.05  ],
       [ 29.    ,   7.8958],
       [ 19.    ,  30.    ],
       [ 33.    ,  90.    ],
       [ 36.    ,  24.15  ],
       [ 29.3728,   7.775 ],
       [ 35.    , 512.3292],
       [ 22.    ,   7.25  ],
       [ 29.3728,  16.1   ],
       [ 18.    ,   7.4958],
       [ 28.    ,  26.    ],
       [ 22.    ,   7.25  ],
       [ 24.    ,   8.05  ],
       [ 22.    ,   9.    ],
       [ 29.3728,  69.55  ],
       [ 26.    ,   7.8958],
       [ 29.    ,  10.4625]])

## Call Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

In [11]:
clf = LogisticRegression()

clf.fit(x_train_trf,y_train)

y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

## Define Missing Indicator

In [12]:
mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [13]:
MissingIndicator()

MissingIndicator()

In [14]:
mi.features_

array([0])

In [16]:
x_train_missing = mi.transform(x_train)

x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True]])

## Transform: Train Missing

In [17]:
x_test_missing = mi.transform(x_test)

x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

## Transform: Test Missing

In [18]:
x_train['Age_NA'] = x_train_missing

x_test

      Age     Fare
707  42.0  26.2875
37   21.0   8.0500
615  24.0  65.0000
169  28.0  56.4958
68   17.0   7.9250
..    ...      ...
89   24.0   8.0500
80   22.0   9.0000
846   NaN  69.5500
870  26.0   7.8958
251  29.0  10.4625

[179 rows x 2 columns]

## Create New Column

In [19]:
x_test['Age_NA'] = x_test_missing

x_train

      Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

## Writing Code again and Check Accuracy

In [20]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.fit_transform(x_test)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
clf = LogisticRegression()
clf.fit(x_train_trf2, y_train)
y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173