#  KNN Imputer

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train (5).csv')[['Age','Pclass','Fare','Survived']]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

## Check Missing Value

In [3]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

## Define X & Y

In [4]:
x = df.drop(columns=['Survived'])
y = df['Survived']

## Train Test Split

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [6]:
x_train

      Age  Pclass      Fare
30   40.0       1   27.7208
10    4.0       3   16.7000
873  47.0       3    9.0000
182   9.0       3   31.3875
876  20.0       3    9.8458
..    ...     ...       ...
534  30.0       3    8.6625
584   NaN       3    8.7125
493  71.0       1   49.5042
527   NaN       1  221.7792
168   NaN       1   25.9250

[712 rows x 3 columns]

## Apply KNN Imputer

In [7]:
knn = KNNImputer(n_neighbors=10,weights='distance')
x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

## Convert in Data Frame

In [8]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  24.278772     3.0    8.7125
709  71.000000     1.0   49.5042
710  31.125155     1.0  221.7792
711  49.076223     1.0   25.9250

[712 rows x 3 columns]

In [9]:
pd.DataFrame(x_train_trf,columns=x_train.columns).sample(10)

      Age  Pclass     Fare
413  36.0     3.0  15.5000
97   28.0     1.0  82.1708
266  31.7     3.0   8.0500
278  40.0     2.0  13.0000
363  48.0     2.0  65.0000
534  32.0     3.0  15.5000
67   26.0     3.0   7.9250
533  21.0     3.0   7.7333
156  32.0     3.0  15.8500
532  28.0     3.0   7.8958

## Apply Logistic Regression

In [10]:
lr = LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7039106145251397